version: 0.1

phases:
  build:
    commands:
      - aws s3 cp s3://builds.myezteam.com/env/prod src/main/resources/env.properties && mvn clean package

artifacts:
  type: ZIP
  files:
    - target/webservices*.jar
    - src/main/resources/prod.yml
    - etc/myezteam-ws.conf
    - bin/application_start.sh